branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/changelog"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: cargo set-version ${nextRelease.version}
  - - "@semantic-release/git"
    - assets:
      - CHANGELOG.md
      - Cargo.lock
      - Cargo.toml
dryRun: true
