[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Molybdenum Software"]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/molybdenumsoftware/pr-tracker"

[workspace.dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from", "deref"] }
pr-tracker-store = { version = "0.1.0", path = "crates/store" }
tempfile = "3.8.1"
util = { version = "0.1.0", path = "crates/util" }
