[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "4.0.0"
authors = ["Molybdenum Software"]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/molybdenumsoftware/pr-tracker"

[workspace.dependencies]
camino = { version = "*", features = ["serde1"] }
confique = { version = "*", default-features = false }
db-context.path = "crates/db-context"
derive_more = { version = "1.0.0-beta.6", features = ["from", "deref"] }
pr-tracker-store.path = "crates/store"
serde = "*"
tempfile = "*"
thiserror = "*"
util.path = "crates/util"

[profile.release]
debug = true
strip = "none"
split-debuginfo = "off"
