[package]
name = "util"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false  # TODO: figure out a better name for this crate before enabling publishing: https://github.com/molybdenumsoftware/pr-tracker/issues/1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db-context.workspace = true
futures = "0.3.29"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.34.0", features = ["process", "macros", "rt", "rt-multi-thread"] }
