[package]
name = "pr-tracker-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pr-tracker-api-config = { path = "../api-config" }
camino = "*"
confique.workspace = true
pr-tracker-store.workspace = true
rocket = { version = "*", features = ["json"] }
rocket_db_pools = { version = "*", features = ["sqlx_postgres"] }
serde.workspace = true
sqlx = { version = "*", default-features = false, features = ["macros", "migrate"] }
thiserror.workspace = true
util.workspace = true

[target.'cfg(target_family = "unix")'.dependencies]
sd-notify = "*"

[dev-dependencies]
db-context.workspace = true
tempfile.workspace = true
tokio = "*"
