[package]
name = "pr-tracker-api-config"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
camino.workspace = true
confique.workspace = true
serde.workspace = true
