[package]
name = "pr-tracker-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { workspace = true, features = ["display"] }
futures = "*"
getset = "*"
sqlx = { version = "*", features = ["postgres", "runtime-tokio"] }
thiserror.workspace = true
