[package]
name = "pr-tracker-store"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more.workspace = true
futures = "0.3.29"
getset = "0.1.2"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio"] }
thiserror.workspace = true
