on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = no-url-literals
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build .#program-docs
          mkdir docs
          cp -r result/share/doc docs/programs
          nix build .#nixos-modules-manual
          cp -r result docs/nixos-modules
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
