on:
  workflow_call:
    outputs:
      token:
        value: ${{ jobs.job.outputs.token }}
    
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: step
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
    outputs:
      token: ${{ steps.step.outputs.token }}
