on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    uses: ./.github/workflows/check.yml

  release:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release-cargo/semantic-release-cargo@2
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
