on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    uses: ./.github/workflows/check.yml

  generate-app-token:
    uses: ./.github/workflows/generate-app-token.yml
    secrets: inherit

  release:
    needs: [check, generate-app-token]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release-cargo/semantic-release-cargo@2
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ needs.generate-app-token.outputs.token }}
